version: 2
jobs:
  test:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-{{ checksum "package.yaml" }}-
            - v1-stack-
          name: Restoring stack cache
      - run:
          name: Test
          command: make test
      - save_cache:
          key: v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          name: Caching stack
          paths:
            - .stack-work
            - /root/.stack
workflows:
  version: 2
  base:
    jobs:
      - test
