version: 2
jobs:
  ghc-8.2.2:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-nix-{{ checksum "package.yaml" }}
            - v1-nix-
          name: Restoring stack cache
      - run:
          name: Compile
          command: nix-shell --run 'make sdist test -j2'
      - save_cache:
          key: v1-nix-{{ checksum "package.yaml" }}
          name: Caching nix
          paths:
            - /nix

  for-github:
    docker:
      - image: alpine
    steps:
      - run:
          name: Passed
          command: echo passed

workflows:
  version: 2
  base:
    jobs:
      - for-github:
          requires:
            - ghc-8.2.2
      - ghc-8.2.2
