version: 2
jobs:
  build:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-root-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-root-{{ checksum "package.yaml" }}-
            - v1-stack-root-
          name: Restoring stack root cache
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-work-{{ checksum "package.yaml" }}-
            - v1-stack-work-
          name: Restoring stack work cache
      - run:
          name: Setup
          command: stack setup
      - run:
          name: Build
          command: stack build --no-run-tests --test
      - run:
          name: Test
          command: stack test
      - save_cache:
          key: v1-stack-root-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          name: Caching stack root
          paths:
            - /root/.stack
      - save_cache:
          key: v1-stack-work-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          name: Caching stack work
          paths:
            - .stack-work
