version: 2
jobs:
  compile:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-{{ checksum "package.yaml" }}-
            - v1-stack-
          name: Restoring stack cache
      - run:
          name: Compile
          command: make build
      - persist_to_workspace:
          root: .make
          paths:
            - '*'
      - persist_to_workspace:
          root: dist
          paths:
            - '*'
      - save_cache:
          key: v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          name: Caching stack
          paths:
            - .stack-work
            - /root/.stack

  sdist:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
            - v1-stack-{{ checksum "package.yaml" }}-
            - v1-stack-
          name: Restoring stack cache
      - run:
          name: Build sdist
          command: make sdist

  test:
    docker:
      - image: haskell:8.2.2
    steps:
      - checkout
      - attach_workspace:
          at: .make
      - attach_workspace:
          at: dist
      - run:
          name: Test
          command: make test

workflows:
  version: 2
  base:
    jobs:
      - compile
      - sdist
      - test:
          requires:
            - compile
